baseURL = 'https://micahjstudio.com'
title = 'micahjstudio'
languageCode = 'en-us'
canonifyURLs = false
relativeURLs = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'TAGS'
pageRef = '/tags/'
weight = 20

[[menus.main]]
name = 'ABOUT'
pageRef = '/about/'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
  [[module.imports]]
    path = "github.com/elecbrandy/freshpink"

[params]
  primaryColor      = "#ec42ff"
  githubUsername    = "elecbrandy"
  showGithubChart   = true
  math = true
  copyright = ''
  mainImage = "/images/compositions.jpeg"
  customCSS = ["css/custom.css"]

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
